// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlspFESCh0eN8MKA-uQk6ieOj_EIZPU7E',
    appId: '1:919574811604:web:dbe084a0584a0ed75ebc41',
    messagingSenderId: '919574811604',
    projectId: 'absence-watch',
    authDomain: 'absence-watch.firebaseapp.com',
    storageBucket: 'absence-watch.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_j4dY8PQ2jKsmMVw45dn4S4uBKeMD3MQ',
    appId: '1:919574811604:android:d52d8e8b6ec53e735ebc41',
    messagingSenderId: '919574811604',
    projectId: 'absence-watch',
    storageBucket: 'absence-watch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRobiusvUTkcMeG78olhG9xLvifxJrfxg',
    appId: '1:919574811604:ios:33b3384fae4e47f25ebc41',
    messagingSenderId: '919574811604',
    projectId: 'absence-watch',
    storageBucket: 'absence-watch.appspot.com',
    iosBundleId: 'com.example.absenceWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRobiusvUTkcMeG78olhG9xLvifxJrfxg',
    appId: '1:919574811604:ios:5ff403b36b03df1a5ebc41',
    messagingSenderId: '919574811604',
    projectId: 'absence-watch',
    storageBucket: 'absence-watch.appspot.com',
    iosBundleId: 'com.example.absenceWatch.RunnerTests',
  );
}
